name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore EchoesOfAshWeb

      - name: Build
        run: dotnet build EchoesOfAshWeb --configuration Release --no-restore

      - name: Publish
        run: dotnet publish EchoesOfAshWeb --configuration Release --no-build -o publish

      - name: Create .nojekyll file
        run: touch publish/wwwroot/.nojekyll

      - name: Update base href
        run: |
          sed -i 's|<base href="/" />|<base href="/EchoesOfAsh/" />|g' publish/wwwroot/index.html

      - name: Copy to docs directory
        run: |
          rm -rf docs
          mkdir -p docs
          cp -r publish/wwwroot/* docs/

      - name: Commit and push changes
        run: |
          git config --global user.name 'GitHub Actions'
          git config --global user.email 'actions@github.com'
          git add docs
          git commit -m "Update GitHub Pages content" || echo "No changes to commit"
          git push
